import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    email: null,
    username: null,
    token: null, 
    isAuthenticated: false,
    phone: null,
    role: null,
};

// createSlice allows you to define the Redux state slice in a single function,
// including the initial state, reducers, and action creators, making it easier to manage state and actions.
// when you create a slice using the createSlice function, it generates two key things: actions and reducer.
const authSlice = createSlice({
    name: "auth", // The name of the slice
    initialState: initialState, // The initial state of the slice
    // reducer functions are accepting the previous state and the action and return the new state
    reducers: {
        loginSuccess(state, action) {
            console.log("login success: ", action.payload.token)
            state.username = action.payload.username;
            state.token = action.payload.token;
            state.email = action.payload.email;
            state.currency = action.payload.currency;
            state.plan = action.payload.plan
            state.isAuthenticated = true;
            state.role = action.payload.role
        },
        logout(state) {
            state.username = null;
            state.token = null;
            state.email = null;
            state.isAuthenticated = false;
        },
        setToken(state, action) {
            state.token = action.payload.token;
        },
        setUsername(state, action) {
            state.username = action.payload.username
        },
        setEmail(state, action) {
            state.email = action.payload.email
        },
        setPhone(state, action) {
            state.phone = action.payload.phone
        },
        setIsAuthenticated(state, action) {
            state.isAuthenticated = action.payload.isAuthenticated
        }
    }
})

// Redux Toolkit will generate action creators for each reducer that you have defined in your slice.
// cartSlice.actions is an object that contains those action creators.
// Here, we extract these specific action creators from the actions object,
// and export them available for import in other files.
export const { loginSuccess, logout, setEmail, setUsername, setIsAuthenticated, setToken, setPhone } = authSlice.actions;

// This line exports the reducer function generated by the createSlice function as the default export from the module.
export default authSlice.reducer;
