import { createSlice } from "@reduxjs/toolkit";

const initialState = {
   todos: [],
   todo: null,
   todayCount: 0,
   overdueCount: 0,
   upcomingCount: 0,
   completedCount: 0,
   loading: false,
   error: null
};

const todoSlice = createSlice({
    name: "todo", 
    initialState: initialState, 
    reducers: {
        setToDo(state, action) {
            state.todo = action.payload
        },
        setToDos(state, action) {
            state.todos = action.payload
        },
        setLoading(state, action) {
            state.loading = action.payload
        },
        setError(state, action) {
            state.error = action.payload
        }
    }
})

// Redux Toolkit will generate action creators for each reducer that you have defined in your slice.
// cartSlice.actions is an object that contains those action creators.
// Here, we extract these specific action creators from the actions object,
// and export them available for import in other files.
export const { setToDo, setToDos, setLoading, setError } = todoSlice.actions;

// This line exports the reducer function generated by the createSlice function as the default export from the module.
export default todoSlice.reducer;
